CBQE-0: fix AttributeError: 'PauseResumeTest' object has no attribute '_timeout'
new tests were added after https://github.com/couchbase/testrunner/commit/83fdf15669cd25683ea200804cd1c52e14877430
changes

Change-Id: I090d2cb59bfff09532fbeb0990fd82cfbc0a0baa
Reviewed-on: http://review.couchbase.org/34991
Reviewed-by: Aruna Piravi <aruna@couchbase.com>
Tested-by: Aruna Piravi <aruna@couchbase.com>