CBQE-0: fix 134 Temporary failure in test_items_append
http://qa.hq.northscale.net/job/centos_x64--51_01--mem_sanity-P1/8/consoleFull
MemcachedError: Memcached error #134 'Temporary failure':  Temporary failure for vbucket :546 to mc 10.1.2.57:11210
ep-engine returned 134 because bucket is out of ram
slightly reduces the number of items

Change-Id: I08da8a1b3bd8e8678b617fd09c70c38e55088ffc
Reviewed-on: http://review.couchbase.org/40676
Tested-by: buildbot <build@couchbase.com>
Reviewed-by: Andrei Baranouski <andrei.baranouski@gmail.com>