Revert "CBQE-4378 Pull builds from nas.build.couchbase.com only if testing ipv6"
This reverts commit 0ed780178cf99033641218084648101307535de8.


http://qa.sc.couchbase.com/job/oel7-1node-QESanity/6/console
install.py fails with the following error
2017-11-30 21:24:42,218 - root - INFO - ********CouchbaseServerInstaller:install
2017-11-30 21:24:42,220 - root - INFO - connecting to 172.23.104.28 with username:root password:couchbase ssh_key:
2017-11-30 21:24:42,391 - root - INFO - Connected to 172.23.104.28
2017-11-30 21:24:42,577 - root - INFO - It could be other operating systyem.  Go to check at other location
Exception in thread installer-thread-172.23.104.28:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "scripts/install.py", line 624, in install
    raise e
KeyError: 'enable_ipv6'

Need to handle the case where enable_ipv6 param is not passed to install.py for backward compatibility

Change-Id: I2440abb6da4b0e6d46126a480c7d4447710137f5
Reviewed-on: http://review.couchbase.org/86240
Reviewed-by: Ritesh Agarwal <ritesh.agarwal@couchbase.com>
Tested-by: Mihir Kamdar <mihir.kamdar@couchbase.com>