MB-100: fix create_connections_test with reb
Traceback (most recent call last):
  File "pytests/connectionstests.py", line 24, in create_connections_test
    rebalance = self.cluster.async_rebalance(self.master, servs_in, [])
  File "lib/couchbase/cluster.py", line 159, in async_rebalance
    _task = RebalanceTask(servers, to_add, to_remove)
  File "lib/tasks/task.py", line 236, in __init__
    self.rest = RestConnection(self.servers[0])
TypeError: 'TestInputServer' object does not support indexing

Change-Id: I6b040d8fee47ba62175ef187a8f5a29f33bde1f2
Reviewed-on: http://review.couchbase.org/25174
Reviewed-by: Andrei Baranouski <andrei.baranouski@gmail.com>
Tested-by: Andrei Baranouski <andrei.baranouski@gmail.com>