CBQE-1027: create data_path directory before server installation
cbenable_core_dumps.sh requires that the data_path folder existed

running command.raw /opt/couchbase/bin/cbenable_core_dumps.sh /data
error: directory /data doesn't exist

Change-Id: Ica9bc86124cb1c1d14f2bb536dab69bbef0e3626
Reviewed-on: http://review.couchbase.org/24403
Reviewed-by: Iryna Mironava <irynamironava@yandex.ru>
Tested-by: buildbot <build@couchbase.com>