Unbreak view-engine tests
When running the view-engine tests via

    scripts/start_cluster_and_run_tests.sh b/resources/dev-single-node.ini conf/view-conf/py-viewmerge.conf

the test suite fails with:

    ======================================================================
    ERROR: test_empty_vbuckets (view.viewmergetests.ViewMergingTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "pytests/view/viewmergetests.py", line 50, in setUp
        self.fail(ex)
    AssertionError: 'services'

The reason is that `services` might not always be set.

Change-Id: Id09eff52d4ecabe1ec38adfb02cfe02eb515af5c
Reviewed-on: http://review.couchbase.org/63032
Reviewed-by: Harsha H S <hhs.couchbase@gmail.com>
Tested-by: Harsha H S <hhs.couchbase@gmail.com>
Reviewed-by: Abhishek Singh <abhishek@couchbase.com>
Tested-by: buildbot <build@couchbase.com>